// AUTO-GENERATED by scripts/sync-theme.mjs — DO NOT EDIT BY HAND.
// Source of truth: ../src/styles/themes.css + globals.css + config/themes.ts (website repo).
// Re-run `npm run sync-theme` to refresh after changing the website theme.
/* eslint-disable */

export type ThemeId = 'forest' | 'sky' | 'light' | 'dark' | 'yotsuba' | 'yotsuba-blue' | 'monokai' | 'commodore' | 'vice' | 'studious' | 'geno';

export type BgImage =
  | { type: 'none' }
  | { type: 'image'; asset: string }
  | { type: 'gradient'; angle: number; stops: string[] };

export interface ThemeTokens {
  footerColor: string;
  bgPrimary: string;
  bgSecondary: string;
  bgHover: string;
  bgCard: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  accent: string;
  accentHover: string;
  accentMuted: string;
  accentFg: string;
  border: string;
  borderStrong: string;
  error: string;
  success: string;
  warning: string;
  navbarBg: string;
  chatBg: string;
  msgSelfBg: string;
  msgOtherBg: string;
  bgImage: BgImage;
  /** When true the theme uses the system font instead of Futura PT. */
  fontOverride: boolean;
}

export interface ThemeMeta {
  id: ThemeId;
  label: string;
  description: string;
}

export const THEME_TOKENS: Record<ThemeId, ThemeTokens> = {
  "light": {
    "bgImage": {
      "type": "none"
    },
    "footerColor": "#6b6b80",
    "bgPrimary": "#ffffff",
    "bgSecondary": "#f4f4f6",
    "bgHover": "#eaeaed",
    "bgCard": "#ffffff",
    "textPrimary": "#111118",
    "textSecondary": "#6b6b80",
    "textMuted": "#9a9aaa",
    "accent": "#6366f1",
    "accentHover": "#4f52e3",
    "accentMuted": "#eef2ff",
    "accentFg": "#ffffff",
    "border": "#e2e2e8",
    "borderStrong": "#c8c8d4",
    "error": "#ef4444",
    "success": "#22c55e",
    "warning": "#f59e0b",
    "navbarBg": "#ffffff",
    "chatBg": "#f9f9fb",
    "msgSelfBg": "#eef2ff",
    "msgOtherBg": "#ffffff",
    "fontOverride": false
  },
  "dark": {
    "bgImage": {
      "type": "none"
    },
    "footerColor": "#9090a8",
    "bgPrimary": "#0e0e12",
    "bgSecondary": "#17171e",
    "bgHover": "#1e1e28",
    "bgCard": "#17171e",
    "textPrimary": "#f0f0f8",
    "textSecondary": "#9090a8",
    "textMuted": "#5a5a70",
    "accent": "#818cf8",
    "accentHover": "#9199fa",
    "accentMuted": "#1e1e3a",
    "accentFg": "#ffffff",
    "border": "#2a2a38",
    "borderStrong": "#3a3a4e",
    "error": "#f87171",
    "success": "#4ade80",
    "warning": "#fbbf24",
    "navbarBg": "#17171e",
    "chatBg": "#0e0e12",
    "msgSelfBg": "#1e1e3a",
    "msgOtherBg": "#17171e",
    "fontOverride": false
  },
  "forest": {
    "bgImage": {
      "type": "image",
      "asset": "gnomguttan_forrest.png"
    },
    "footerColor": "#3d5e1e",
    "bgPrimary": "#c8e89a",
    "bgSecondary": "#b5d880",
    "bgHover": "#a4c86e",
    "bgCard": "#ffffff",
    "textPrimary": "#1a2e0a",
    "textSecondary": "#3d5e1e",
    "textMuted": "#6a8a50",
    "accent": "#2d7d32",
    "accentHover": "#1b5e20",
    "accentMuted": "#e8f5e9",
    "accentFg": "#ffffff",
    "border": "#9dcc60",
    "borderStrong": "#78a840",
    "error": "#c62828",
    "success": "#2e7d32",
    "warning": "#e65100",
    "navbarBg": "#c8e89a",
    "chatBg": "#f4fce8",
    "msgSelfBg": "#dcf0b8",
    "msgOtherBg": "#ffffff",
    "fontOverride": false
  },
  "yotsuba": {
    "bgImage": {
      "type": "gradient",
      "angle": 180,
      "stops": [
        "#fed7b0",
        "#feffed"
      ]
    },
    "footerColor": "#317354",
    "bgPrimary": "#feffed",
    "bgSecondary": "#f8c89a",
    "bgHover": "#f0b880",
    "bgCard": "#f1e0d6",
    "textPrimary": "#9c1a1d",
    "textSecondary": "#317354",
    "textMuted": "#9aac81",
    "accent": "#317354",
    "accentHover": "#225540",
    "accentMuted": "#e4ede0",
    "accentFg": "#ffffff",
    "border": "#f0c490",
    "borderStrong": "#dba870",
    "error": "#99444b",
    "success": "#317354",
    "warning": "#d06820",
    "navbarBg": "#fed6b0",
    "chatBg": "#f1e0d6",
    "msgSelfBg": "#e4ede0",
    "msgOtherBg": "#f1e0d6",
    "fontOverride": true
  },
  "yotsuba-blue": {
    "bgImage": {
      "type": "gradient",
      "angle": 180,
      "stops": [
        "#d1d5ee",
        "#eff2fc"
      ]
    },
    "footerColor": "#317354",
    "bgPrimary": "#eff2fc",
    "bgSecondary": "#e2e6f4",
    "bgHover": "#d5daf0",
    "bgCard": "#d5daf0",
    "textPrimary": "#202b3b",
    "textSecondary": "#317354",
    "textMuted": "#9aac81",
    "accent": "#171e60",
    "accentHover": "#0e1345",
    "accentMuted": "#e8eaf8",
    "accentFg": "#ffffff",
    "border": "#c8cde8",
    "borderStrong": "#aab0d8",
    "error": "#99444b",
    "success": "#317354",
    "warning": "#d06820",
    "navbarBg": "#d1d5ee",
    "chatBg": "#d5daf0",
    "msgSelfBg": "#e8eaf8",
    "msgOtherBg": "#d5daf0",
    "fontOverride": true
  },
  "monokai": {
    "bgImage": {
      "type": "none"
    },
    "footerColor": "#bcc865",
    "bgPrimary": "#2f2a2e",
    "bgSecondary": "#403e42",
    "bgHover": "#504d52",
    "bgCard": "#403e42",
    "textPrimary": "#f7f4f7",
    "textSecondary": "#bcc865",
    "textMuted": "#63cfca",
    "accent": "#fe4d84",
    "accentHover": "#e03070",
    "accentMuted": "#3d1520",
    "accentFg": "#ffffff",
    "border": "#504d52",
    "borderStrong": "#635f65",
    "error": "#e8936a",
    "success": "#bcc865",
    "warning": "#e8936a",
    "navbarBg": "#2f2a2e",
    "chatBg": "#2f2a2e",
    "msgSelfBg": "#403e42",
    "msgOtherBg": "#2f2a2e",
    "fontOverride": false
  },
  "commodore": {
    "bgImage": {
      "type": "none"
    },
    "footerColor": "#4a4845",
    "bgPrimary": "#b8b3aa",
    "bgSecondary": "#a8a39a",
    "bgHover": "#9a958e",
    "bgCard": "#cac5bc",
    "textPrimary": "#012383",
    "textSecondary": "#277dbf",
    "textMuted": "#7a7875",
    "accent": "#d80e30",
    "accentHover": "#a80825",
    "accentMuted": "#fefbe0",
    "accentFg": "#ffffff",
    "border": "#ee7d17",
    "borderStrong": "#d80e30",
    "error": "#d80e30",
    "success": "#47cb33",
    "warning": "#ee7d17",
    "navbarBg": "#b8b3aa",
    "chatBg": "#cac5bc",
    "msgSelfBg": "#fefbe0",
    "msgOtherBg": "#cac5bc",
    "fontOverride": false
  },
  "vice": {
    "bgImage": {
      "type": "gradient",
      "angle": 135,
      "stops": [
        "#415cd5",
        "#f44db9",
        "#e78557"
      ]
    },
    "footerColor": "#fcb923",
    "bgPrimary": "#1e1030",
    "bgSecondary": "#1a0c28",
    "bgHover": "#2d1a40",
    "bgCard": "#231530",
    "textPrimary": "#fcfcfc",
    "textSecondary": "#f44db9",
    "textMuted": "#9e1a65",
    "accent": "#fcb923",
    "accentHover": "#e0a010",
    "accentMuted": "#2d2010",
    "accentFg": "#1a0c28",
    "border": "#aa51b2",
    "borderStrong": "#f44db9",
    "error": "#9e1a65",
    "success": "#e78557",
    "warning": "#fcb923",
    "navbarBg": "#1e1030",
    "chatBg": "#231530",
    "msgSelfBg": "#2d2010",
    "msgOtherBg": "#231530",
    "fontOverride": false
  },
  "studious": {
    "bgImage": {
      "type": "none"
    },
    "footerColor": "#555555",
    "bgPrimary": "#0d0d0d",
    "bgSecondary": "#1a1a1a",
    "bgHover": "#2a2a2a",
    "bgCard": "#222222",
    "textPrimary": "#f0f0f0",
    "textSecondary": "#aaaaaa",
    "textMuted": "#555555",
    "accent": "#dc1011",
    "accentHover": "#b50d0e",
    "accentMuted": "#1f0505",
    "accentFg": "#ffffff",
    "border": "#2a2a2a",
    "borderStrong": "#3a3a3a",
    "error": "#dc1011",
    "success": "#3a9e3a",
    "warning": "#b87020",
    "navbarBg": "#0d0d0d",
    "chatBg": "#111111",
    "msgSelfBg": "#1f0505",
    "msgOtherBg": "#222222",
    "fontOverride": false
  },
  "geno": {
    "bgImage": {
      "type": "gradient",
      "angle": 180,
      "stops": [
        "#021a03",
        "#0a6e0e",
        "#542814",
        "#050505"
      ]
    },
    "footerColor": "#ad6f46",
    "bgPrimary": "#0a1005",
    "bgSecondary": "#151a08",
    "bgHover": "#1e2510",
    "bgCard": "#1a1205",
    "textPrimary": "#ffd37d",
    "textSecondary": "#ffc53e",
    "textMuted": "#ad6f46",
    "accent": "#ffc53e",
    "accentHover": "#e0a020",
    "accentMuted": "#2a1e05",
    "accentFg": "#0a1005",
    "border": "#3a6a4a",
    "borderStrong": "#2a5038",
    "error": "#ad3840",
    "success": "#08cd0d",
    "warning": "#ffc53e",
    "navbarBg": "#0a1005",
    "chatBg": "#1a1205",
    "msgSelfBg": "#2a1e05",
    "msgOtherBg": "#1a1205",
    "fontOverride": false
  },
  "sky": {
    "bgImage": {
      "type": "image",
      "asset": "gnomguttan_sky.png"
    },
    "footerColor": "#111118",
    "bgPrimary": "#2b7ec9",
    "bgSecondary": "#1e6eb8",
    "bgHover": "#1a5fa4",
    "bgCard": "#0d2b45",
    "textPrimary": "#e3f2fd",
    "textSecondary": "#90caf9",
    "textMuted": "#64b5f6",
    "accent": "#29b6f6",
    "accentHover": "#03a9f4",
    "accentMuted": "#0d3a6e",
    "accentFg": "#ffffff",
    "border": "#1a4f8a",
    "borderStrong": "#1565c0",
    "error": "#ef9a9a",
    "success": "#a5d6a7",
    "warning": "#ffe082",
    "navbarBg": "#2b7ec9",
    "chatBg": "#0a1e32",
    "msgSelfBg": "#0d3a6e",
    "msgOtherBg": "#0d2b45",
    "fontOverride": false
  }
} as any;

export const THEME_LIST: ThemeMeta[] = [
  {
    "id": "forest",
    "label": "Forest",
    "description": "Green & natural"
  },
  {
    "id": "sky",
    "label": "Sky",
    "description": "Blue & open"
  },
  {
    "id": "light",
    "label": "Light",
    "description": "Clean & bright"
  },
  {
    "id": "dark",
    "label": "Dark",
    "description": "Easy on the eyes"
  },
  {
    "id": "yotsuba",
    "label": "Yotsuba",
    "description": "Warm & cheerful"
  },
  {
    "id": "yotsuba-blue",
    "label": "Yotsuba Blue",
    "description": "Cool & calm"
  },
  {
    "id": "monokai",
    "label": "Monokai",
    "description": "Dark & vivid"
  },
  {
    "id": "commodore",
    "label": "Commodore",
    "description": "Retro & bold"
  },
  {
    "id": "vice",
    "label": "Vice",
    "description": "Mellow gradient"
  },
  {
    "id": "studious",
    "label": "Studious",
    "description": "Dark & focused"
  },
  {
    "id": "geno",
    "label": "Geno",
    "description": "Lush and Mysterious"
  }
] as any;

export const DEFAULT_THEME_ID: ThemeId = "forest" as any;

export const RADIUS = {
  "sm": 6,
  "md": 10,
  "lg": 16,
  "full": 9999
};

// Static require map so Metro bundles the background images.
export const BACKGROUND_IMAGES: Record<string, number> = {
  'gnomguttan_forrest.png': require('../../assets/backgrounds/gnomguttan_forrest.png'),
  'gnomguttan_sky.png': require('../../assets/backgrounds/gnomguttan_sky.png'),
};
