services:
  gnomguttan:
    image: ghcr.io/jensmjahle/gnomguttan-app:latest
    container_name: gnomguttan
    ports:
      - "3001:80"
    environment:
      VOCECHAT_HOST: https://chat.gnomguttan.no
      APP_TITLE: Gnomguttan
    restart: unless-stopped
