services:
  gnomguttan:
    image: ghcr.io/jensmjahle/gnomguttan:latest
    container_name: gnomguttan
    ports:
      - "3001:3001"
    environment:
      PORT: ${PORT:-3001}
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB: ${MONGODB_DB:-}
      VOCECHAT_HOST: ${VOCECHAT_HOST:-https://chat.gnomguttan.no}
      APP_TITLE: ${APP_TITLE:-Gnomguttan}
      VOCECHAT_BOT_TARGET_GROUP_ID: ${VOCECHAT_BOT_TARGET_GROUP_ID:-}
      VOCECHAT_BOT_API_KEY: ${VOCECHAT_BOT_API_KEY:-}
      JELLYFIN_HOST: ${JELLYFIN_HOST:-}
      JELLYFIN_CLIENT_URL: ${JELLYFIN_CLIENT_URL:-https://kino.gnomguttan.no}
      JELLYFIN_TOKEN: ${JELLYFIN_TOKEN:-}
    restart: unless-stopped
