const PHRASES = {
  '30m': [
    (name, title) => `@${name} hei! Du har ikke svart på "${title}" ennå. Bare gi oss en tilbakemelding når du kan 😊`,
    (name, title) => `@${name} liten påminnelse – "${title}" venter på svar fra deg!`,
    (name, title) => `@${name} husker du "${title}"? Vi trenger svaret ditt 🙏`,
    (name, title) => `@${name} bare for å si fra – du har ikke svart på "${title}" ennå.`,
    (name, title) => `@${name} poke poke 👉 "${title}" trenger svar fra deg!`,
    (name, title) => `@${name} skulle bare mangle at du svarte på "${title}" nå da 😊`,
    (name, title) => `@${name} tok du kanskje ikke imot? "${title}" mangler svar fra deg`,
    (name, title) => `@${name} ett lite pip om "${title}"? Bare svar fort 😄`,
    (name, title) => `@${name} vi lover det tar bare 2 sekunder å svare på "${title}"`,
    (name, title) => `@${name} du har kanskje glemt "${title}"? Her er en vennlig påminnelse`,
    (name, title) => `@${name} hilser og spør – har du sett "${title}" enda?`,
    (name, title) => `@${name} ikke stress, men "${title}" venter på svar fra deg 😊`,
    (name, title) => `@${name} bare en liten ting – "${title}" har ikke fått svar fra deg`,
    (name, title) => `@${name} du er den eneste som ikke har svart på "${title}" ennå`,
    (name, title) => `@${name} vi setter veldig pris på om du svarer på "${title}" 🙏`,
    (name, title) => `@${name} det var så hyggelig at du ble invitert – svar på "${title}" da vel!`,
    (name, title) => `@${name} ta en titt på "${title}" og gi oss beskjed? 🥺`,
    (name, title) => `@${name} du har kanskje ikke sett "${title}"? Her er linken igjen`,
    (name, title) => `@${name} svar på "${title}" gjør arrangementet enda bedre!`,
    (name, title) => `@${name} vi gleder oss til å høre fra deg om "${title}" 😊`,
  ],

  '2h': [
    (name, title) => `@${name} oi, fortsatt ingen svar på "${title}"? Tar ikke lang tid å svare, din gnom!`,
    (name, title) => `@${name} to timer siden du fikk invitasjonen til "${title}" og ingenting. Svaaaaaaaar.`,
    (name, title) => `@${name} klarer du ikke å ta deg tid til å svare på "${title}"? Det er ett klikk, mann.`,
    (name, title) => `@${name} vi venter fortsatt på deg. "${title}". Svar nå.`,
    (name, title) => `@${name} nei altså. "${title}" har stått og ventet på svar fra deg i to timer nå.`,
    (name, title) => `@${name} seriøst? To timer og fortsatt null svar på "${title}"? Pinlig.`,
    (name, title) => `@${name} du er treg i dag? "${title}" venter. Svar.`,
    (name, title) => `@${name} 120 minutter. Det er alt du har hatt på deg til å svare på "${title}". Hva venter du på?`,
    (name, title) => `@${name} du har fortsatt ikke svart på "${title}". Det begynner å bli litt flaut.`,
    (name, title) => `@${name} to timer. Man rekker å se en film på den tida. Du rekker ikke å trykke på "${title}". Hæh?`,
    (name, title) => `@${name} du gir meg flashbacks til treige kolleger. "${title}" – svar for faen.`,
    (name, title) => `@${name} hvordan har du det egentlig? Svar på "${title}" så vet jeg at du lever.`,
    (name, title) => `@${name} jeg teller sekundene. 7200 sekunder uten svar på "${title}". Føles bra?`,
    (name, title) => `@${name} du har blitt stemplet som "ikke-svarer" på "${title}". Vil du endre det?`,
    (name, title) => `@${name} treg som sirup på en kald dag. "${title}" trenger svar fra deg NÅ.`,
    (name, title) => `@${name} altså, det er 2026, du har en mobil i lomma. Svar på "${title}" da vel!`,
    (name, title) => `@${name} hvis du ikke svarer på "${title}" snart, begynner jeg å ta det personlig.`,
    (name, title) => `@${name} du ser sikkert denne. Du ignorerer den. Og jeg blir mer og mer irritert på "${title}"-greia.`,
    (name, title) => `@${name} to timer med stillhet om "${title}". Ikke kult. Svar.`,
    (name, title) => `@${name} du tror kanskje jeg gir meg? Nei. "${title}" – svar!`,
  ],

  '8h': [
    (name, title) => `@${name} åtte timer. ÅTTE TIMER og du har ikke giddet å svare på "${title}". Kom igjen nå.`,
    (name, title) => `@${name} er du død? Svar på "${title}" med en gang din dovne gnom.`,
    (name, title) => `@${name} dette er tredje purring. "${title}". Svar. Nå.`,
    (name, title) => `@${name} har mobilen din gått i vasken eller? Svar på "${title}" for faen!`,
    (name, title) => `@${name} alle andre har svart på "${title}". Bare du ikke. Typisk.`,
    (name, title) => `@${name} 8 timer uten svar på "${title}" – er du seriøst så lat?`,
    (name, title) => `@${name} nå begynner jeg å bli forbanna. "${title}" – SVAR!`,
    (name, title) => `@${name} du tror du er kul som ignorerer "${title}"? Det er du ikke.`,
    (name, title) => `@${name} jeg har sendt deg tre meldinger om "${title}" uten respons. Dette er den fjerde. Og siste før jeg blir sint.`,
    (name, title) => `@${name} du har 8 timer på samvittigheten. Åtte timer med total ignorering av "${title}". Hva har du å si for deg?`,
    (name, title) => `@${name} svar på "${title}" ELLERS kommer jeg til å bli veldig frustrert. Og det vil du ikke oppleve.`,
    (name, title) => `@${name} ga du faen? I så fall – svar på "${title}" før jeg mister det totalt.`,
    (name, title) => `@${name} 8 timer. Det hadde holdt til å gå tur til Sverige og tilbake. Du har ikke svart på "${title}". Patetisk.`,
    (name, title) => `@${name} du er den eneste som ikke har svart på "${title}" nå. Skjerp deg.`,
    (name, title) => `@${name} jeg gir deg beskjed nå: hvis du ikke svarer på "${title}" ila de neste 5 minuttene, kommer jeg til å bli forbanna.`,
    (name, title) => `@${name} du har offisielt overgått min tålmodighet. "${title}" – svar eller jeg begynner å true deg.`,
    (name, title) => `@${name} dette er siste vennlige påminnelse. "${title}". Neste gang blir det verre.`,
    (name, title) => `@${name} du vil ikke like meg når jeg er sint. Og du er i ferd med å gjøre meg sint. "${title}".`,
    (name, title) => `@${name} 8 timer med stillhet. Jeg lurer på om du faktisk er i live eller bare totalt uinteressert. "${title}"?`,
    (name, title) => `@${name} greit, jeg har prøvd pent. Nå blir det stygt. "${title}" – SVAR, din ordentlige tregpost!`,
  ],

  '24h': [
    (name, title) => `@${name} ETT HELT DØGN og du har ikke svart på "${title}". Hva driver du med?!`,
    (name, title) => `@${name} du har fortsatt ikke svart på "${title}". Svar med en jævla gang din rotteknuller.`,
    (name, title) => `@${name} vi har ventet i 24 timer på svar fra deg på "${title}". Dette er ikke greit.`,
    (name, title) => `@${name} ett døgn siden "${title}" ble lagt ut. Svaret ditt glimrer med sitt fravær.`,
    (name, title) => `@${name} kossen er det mulig å ikke svare på "${title}" på ett helt døgn? Kom deg inn og svar!`,
    (name, title) => `@${name} 24 timer. 24 timer uten et jævla pip om "${title}". Du er en drittsekk.`,
    (name, title) => `@${name} jeg begynner å miste troen på deg. "${title}" – SVAR NÅ DIN JÆVLA GNOM!`,
    (name, title) => `@${name} ett døgn. Hele 24 timer. Du har ikke engang giddet å åpne "${title}"?`,
    (name, title) => `@${name} du tror du er bedre enn oss? "${title}" venter. Svar din jævel.`,
    (name, title) => `@${name} hvis du ikke svarer på "${title}" i løpet av den neste timen, kommer jeg til å spamme deg til du klikker.`,
    (name, title) => `@${name} 24 timer med total ignorering. Jeg har vært tålmodig. Nok er nok. "${title}"!`,
    (name, title) => `@${name} du gjør meg forbanna nå. Svar på "${title}" din ubrukelige idiot!`,
    (name, title) => `@${name} du har hatt 24 timer på deg. Det er mer enn nok. "${title}" – svar eller jeg ser deg IRL.`,
    (name, title) => `@${name} du er en skam. Svar på "${title}" din latsabb.`,
    (name, title) => `@${name} jeg har ikke tid til å sende deg flere påminnelser. "${title}". SVAR. JÆVLA. NÅ.`,
    (name, title) => `@${name} du har ignorert "${title}" i 24 timer. Jeg begynner å lure på om du er en bots.`,
    (name, title) => `@${name} dette er en direkte advarsel: svar på "${title}" eller jeg kommer til å bli veldig uhyggelig.`,
    (name, title) => `@${name} 24 timer. Og ingenting. Du er utrolig frekk. "${title}" – svar.`,
    (name, title) => `@${name} du tror du kan ignorere meg? Svar på "${title}" din dumme faen!`,
    (name, title) => `@${name} jeg gir deg 5 minutter på å svare på "${title}" før jeg eskalerer dette.`,
  ],

  '48h': [
    (name, title) => `@${name} TO DAGER! To jævla dager uten svar på "${title}". Hva pokker er det som foregår hos deg?`,
    (name, title) => `@${name} er du faen meg seriøs? 48 timer og ingen svar på "${title}"? Svar NÅ din idiot.`,
    (name, title) => `@${name} vi vet du har sett dette. Svar på "${title}" eller så forteller vi alle at du er en dårlig venn.`,
    (name, title) => `@${name} dette begynner å bli personlig. "${title}". SV-AR.`,
    (name, title) => `@${name} 48 timer. Hadde klart å gå til og fra Nordpolen på den tida. Du klarer ikke å svare på "${title}".`,
    (name, title) => `@${name} du er fullstendig ubrukelig. To dager uten svar på "${title}"? Du driver galskap.`,
    (name, title) => `@${name} nå har jeg fått nok. Svar på "${title}" eller jeg sørger for at du blir kastet ut.`,
    (name, title) => `@${name} 48 timer med stillhet. Jeg vurderer å blokkere deg hvis du ikke svarer på "${title}" innen en time.`,
    (name, title) => `@${name} du er en komplett taper. "${title}" har ventet i to dager og du gir blaffen.`,
    (name, title) => `@${name} jeg har prøvd å være hyggelig. Det slutter nå. "${title}" – svar før jeg blir voldelig.`,
    (name, title) => `@${name} to dager. To dager med total ignorering. Dette er krig. "${title}" – svar.`,
    (name, title) => `@${name} du har valgt å ignorere "${title}" i 48 timer. Det får konsekvenser.`,
    (name, title) => `@${name} jeg gir deg 10 minutter. Hvis du ikke har svart på "${title}" da, kommer jeg til å gjøre noe dramatisk.`,
    (name, title) => `@${name} du tror du er tøff? Svar på "${title}" din feige drittsekk.`,
    (name, title) => `@${name} 48 timer. Det er lenge nok til å bli skikkelig forbanna. "${title}" – SVAR!`,
    (name, title) => `@${name} du har offisielt mistet min respekt. Men du kan få den tilbake – svar på "${title}".`,
    (name, title) => `@${name} to dager uten svar. Jeg har sendt deg 10 meldinger. Du har ignorert alle. "${title}" – dette er siste sjanse.`,
    (name, title) => `@${name} hvis du ikke svarer på "${title}" nå, kommer jeg til å poste fingerbilde ditt på gruppa. Så skjerp deg.`,
    (name, title) => `@${name} du er i ferd med å bli en legende – av feighet. "${title}" – svar din jævel.`,
    (name, title) => `@${name} jeg har funnet adressen din, bare så du vet det. Svar på "${title}" eller jeg kommer på besøk.`,
  ],

  '72h': [
    (name, title) => `FAEN I HELVETE @${name}! TRE DAGER og ikke et pip fra deg om "${title}". Hvis du ikke svarer nå så kommer jeg og skjærer av deg forhuden mens du sover.`,
    (name, title) => `@${name} 72 timer. SYVTI-TO TIMER. "${title}". SV-AR-PÅ-FAE-N-MEG.`,
    (name, title) => `@${name} jeg er lei av å sende deg disse påminnelsene. Svar på "${title}" eller jeg gir opp deg som menneske.`,
    (name, title) => `@${name} dette er en krisetilstand. Tre dager uten svar på "${title}". Hva er galt med deg?`,
    (name, title) => `@${name} vi har sendt deg seks purringer om "${title}". SEKS. Svar eller bli bannlyst fra gnomguttan for livet.`,
    (name, title) => `@${name} du har tre dager på å finne ut av livet ditt. Svar på "${title}" eller jeg jager deg.`,
    (name, title) => `@${name} jeg drømmer om å finne deg og trykke ansiktet ditt ned i telefonen til du svarer på "${title}".`,
    (name, title) => `@${name} 72 timer. Det tar 3 dager å lage en baby. Du har ikke engang svart på "${title}". Skam deg.`,
    (name, title) => `@${name} du er i ferd med å oppleve en vrede du ikke aner. "${title}" – svar din jævla drittsekk.`,
    (name, title) => `@${name} jeg har ventet i 72 timer. Nå har jeg null tålmodighet igjen. Svar på "${title}" eller jeg kommer og brenner huset ditt.`,
    (name, title) => `@${name} tre dager. Hele tre dager. Du har ignorert "${title}" som om det var søppel. Det skal du få svi for.`,
    (name, title) => `@${name} hvis du ikke svarer på "${title}" innen 24 timer til, skal jeg kontakte moren din.`,
    (name, title) => `@${name} du er død for meg hvis du ikke svarer på "${title}" nå. Bokstavelig talt. Jeg kommer til å drepe deg.`,
    (name, title) => `@${name} 72 timer uten svar. Jeg har ringt deg 12 ganger. Du tar ikke telefonen. Svar på "${title}" før jeg mister det helt.`,
    (name, title) => `@${name} du er den mest frekke personen jeg vet om. "${title}" – SVAR ELLER JEG KNUSER TELEFONEN DIN.`,
    (name, title) => `@${name} jeg gir ikke faen om du er syk eller i begravelse. Svar på "${title}" din ordentlige drittsekk.`,
    (name, title) => `@${name} dette er ikke en trussel, men en fakta: hvis du ikke svarer på "${title}" snart, kommer jeg til å skade deg.`,
    (name, title) => `@${name} tre dager. Jeg har sendt bud på deg. Du er ikke verdt tiden min. Men svar på "${title}" nå!`,
    (name, title) => `@${name} du har 1 time. Deretter begynner jeg å stikke hull på dekkene dine. Svar på "${title}".`,
    (name, title) => `@${name} faen ta deg. 72 timer. "${title}" – svar eller jeg lover at du kommer til å angre.`,
  ],

  'every5d': [
    (name, title) => `NÅ ER DET FAEN MEG NOK @${name}! DU HAR FORTSATT IKKE SVART PÅ "${title}" DIN JÆVLA FEITE FAEN!!!! Gå inn å svar med en gang, ellers kommer jeg og finner deg.`,
    (name, title) => `@${name} VET DU HVA? JEG GIR FAEN. Men svar på "${title}" da vel. FOR HELVETE.`,
    (name, title) => `@${name} vi har kommet til det punktet der jeg faktisk begynner å lure på om du er i live. Svar på "${title}" som et tegn på at du eksisterer.`,
    (name, title) => `@${name} SVAR PÅ "${title}" ELLER JEG MELDER DEG UT AV GRUPPA. DETTE ER IKKE EN TRUSSEL, DETTE ER ET LØFTE.`,
    (name, title) => `@${name} dagene går. Arrangementet "${title}" nærmer seg. Du har FORTSATT ikke svart. Jeg er lei meg på dine vegne. Og rasende. Mest rasende.`,
    (name, title) => `@${name} du har offisielt blitt erklært som fiende av staten. Svar på "${title}" eller bli tilintetgjort.`,
    (name, title) => `@${name} jeg kommer til å poste en dump på deg på r/norge hvis du ikke svarer på "${title}" om 5 minutter.`,
    (name, title) => `@${name} du er så treg at jeg vurderer å sende en snikskytter etter deg. Svar på "${title}"!`,
    (name, title) => `@${name} hvis du ikke svarer på "${title}" i dag, kommer jeg til å spørre alle vennene dine om de har sett deg, i en offentlig post. Pinlig? Ja.`,
    (name, title) => `@${name} JEG HAR EN ØKS. OG EN PLAN. Svar på "${title}" før jeg setter planen i verk.`,
    (name, title) => `@${name} du vet hva? JEG ER IKKE SINN. JEG ER SKUFFET. Og skuffede folk gjør desperate ting. Svar på "${title}".`,
    (name, title) => `@${name} dette er din siste advarsel. Jeg har koblet meg opp til personvernet ditt. Jeg vet alt om deg. Svar på "${title}" eller jeg legger ut alt på nettet.`,
    (name, title) => `@${name} du har 48 timer på å svare på "${title}" før jeg begynner å sende deg regninger for psykisk helsevern.`,
    (name, title) => `@${name} jeg har opprettet en egen gruppe dedikert til å hate deg. Den er ganske populær. Vil du unngå mer hat? Svar på "${title}".`,
    (name, title) => `@${name} SVAR PÅ "${title}" ELLER JEG FÅR BESTEFAREN MIN TIL Å HJEMSØKE DEG. HAN VAR GRUSOM.`,
    (name, title) => `@${name} du er et mysterium. Et veldig irriterende mysterium. Løs gåten ved å svare på "${title}".`,
    (name, title) => `@${name} jeg har nå sendt 20 påminnelser om "${title}". Du har ignorert alle. Nå får du skylden for alt som skjer.`,
    (name, title) => `@${name} jeg gir deg 5 sekunder. 5-4-3-2-1… Svar på "${title}" eller jeg knuser telefonen din mentalt.`,
    (name, title) => `@${name} jeg har installert en app som sender meg varsel hver gang du åpner telefonen. Jeg vet at du ser dette. Svar på "${title}" din jævel.`,
    (name, title) => `@${name} OK, NÅ ER DET NOK. Jeg kommer til å møte deg på døren din med en vannpistol fylt med eddik hvis du ikke svarer på "${title}". Siste sjanse.`,
  ],
};
export function getRandomReminderPhrase(stageKey, userName, eventTitle) {
  const key = stageKey.startsWith('5d-') ? 'every5d' : stageKey;
  const pool = PHRASES[key] ?? PHRASES['every5d'];
  const fn = pool[Math.floor(Math.random() * pool.length)];
  return fn(userName, eventTitle);
}
